/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.krispeklaric.virgohospital_gui;

import com.sun.glass.events.KeyEvent;

/**
 *
 * @author Kris
 */
public class ExtensiveForm extends javax.swing.JDialog {

    public ExtensiveForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLabelExtensiveForm = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jComboBoxSex3 = new javax.swing.JComboBox<>();
        jTextField4 = new javax.swing.JTextField();
        jLabelBirthdate3 = new javax.swing.JLabel();
        jFormattedTextFieldBirthdate3 = new javax.swing.JFormattedTextField();
        jLabelFirstname3 = new javax.swing.JLabel();
        jTextFieldFirstName3 = new javax.swing.JTextField();
        jLabelMiddle3 = new javax.swing.JLabel();
        jTextFieldMiddleName3 = new javax.swing.JTextField();
        jTextFieldSurname3 = new javax.swing.JTextField();
        jLabelSurname3 = new javax.swing.JLabel();
        jLabelSex3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldFirstName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldFirstName1 = new javax.swing.JTextField();
        jTextFieldFirstName2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jFormattedTextFieldBirthdate = new javax.swing.JFormattedTextField();
        jLabelBirthdate = new javax.swing.JLabel();
        jLabelBirthdate1 = new javax.swing.JLabel();
        jFormattedTextFieldBirthdate1 = new javax.swing.JFormattedTextField();
        jLabelBirthdate2 = new javax.swing.JLabel();
        jFormattedTextFieldBirthdate2 = new javax.swing.JFormattedTextField();
        jLabelBirthdate4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jFormattedTextFieldBirthdate4 = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabelBirthdate5 = new javax.swing.JLabel();
        jTextFieldFirstName4 = new javax.swing.JTextField();
        jFormattedTextFieldBirthdate5 = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldFirstName5 = new javax.swing.JTextField();
        jTextFieldFirstName6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jFormattedTextFieldBirthdate6 = new javax.swing.JFormattedTextField();
        jLabelBirthdate6 = new javax.swing.JLabel();
        jFormattedTextFieldPhoneNum = new javax.swing.JFormattedTextField();
        jLabelBirthdate7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jFormattedTextFieldPhoneNum1 = new javax.swing.JFormattedTextField();
        jLabelBirthdate8 = new javax.swing.JLabel();
        jFormattedTextFieldPhoneNum2 = new javax.swing.JFormattedTextField();
        jLabelBirthdate9 = new javax.swing.JLabel();
        jTextFieldFirstName7 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldFirstName8 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldFirstName9 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jFormattedTextFieldPhoneNum3 = new javax.swing.JFormattedTextField();
        jLabelBirthdate10 = new javax.swing.JLabel();
        jTextFieldFirstName10 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldFirstName11 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldFirstName12 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jFormattedTextFieldPhoneNum4 = new javax.swing.JFormattedTextField();
        jLabelBirthdate11 = new javax.swing.JLabel();
        jFormattedTextFieldPhoneNum5 = new javax.swing.JFormattedTextField();
        jLabelBirthdate12 = new javax.swing.JLabel();
        jLabelFirstname4 = new javax.swing.JLabel();
        jTextFieldFirstName13 = new javax.swing.JTextField();
        jLabelMiddle4 = new javax.swing.JLabel();
        jTextFieldMiddleName4 = new javax.swing.JTextField();
        jTextFieldSurname4 = new javax.swing.JTextField();
        jLabelSurname4 = new javax.swing.JLabel();
        jLabelBirthdate13 = new javax.swing.JLabel();
        jFormattedTextFieldBirthdate7 = new javax.swing.JFormattedTextField();
        jLabelBirthdate14 = new javax.swing.JLabel();
        jFormattedTextFieldBirthdate8 = new javax.swing.JFormattedTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldFirstName14 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextFieldFirstName15 = new javax.swing.JTextField();
        jTextFieldFirstName16 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jFormattedTextFieldBirthdate9 = new javax.swing.JFormattedTextField();
        jLabelBirthdate15 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButtonCancel = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JLabelExtensiveForm.setFont(new java.awt.Font("Tahoma", 0, 27)); // NOI18N
        JLabelExtensiveForm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelExtensiveForm.setText("Extensive Form");

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jComboBoxSex3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));

        jTextField4.setEnabled(false);

        jLabelBirthdate3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelBirthdate3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelBirthdate3.setText("Date of Birth(dd/mm/yyyy):");

        jFormattedTextFieldBirthdate3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        jFormattedTextFieldBirthdate3.setText("01/01/2000");

        jLabelFirstname3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelFirstname3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelFirstname3.setText("First name:");

        jTextFieldFirstName3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldFirstName3jTextFieldOnlyAplhabeticKeyTyped(evt);
            }
        });

        jLabelMiddle3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelMiddle3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelMiddle3.setText("Middle name:");

        jTextFieldMiddleName3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldMiddleName3KeyTyped(evt);
            }
        });

        jTextFieldSurname3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldSurname3KeyTyped(evt);
            }
        });

        jLabelSurname3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelSurname3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelSurname3.setText("Surname:");

        jLabelSex3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelSex3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelSex3.setText("Sex(M/F):");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Outpatient ID (OPID):");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jLabelBirthdate3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFormattedTextFieldBirthdate3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabelFirstname3)
                            .addComponent(jLabelMiddle3)
                            .addComponent(jLabelSurname3)
                            .addComponent(jLabelSex3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextFieldSurname3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldFirstName3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldMiddleName3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBoxSex3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(340, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFirstname3)
                    .addComponent(jTextFieldFirstName3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMiddle3)
                    .addComponent(jTextFieldMiddleName3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSurname3)
                    .addComponent(jTextFieldSurname3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSex3)
                    .addComponent(jComboBoxSex3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBirthdate3)
                    .addComponent(jFormattedTextFieldBirthdate3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(137, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Basic Details", jPanel1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Telephones/Fax/Email");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("State:");

        jTextFieldFirstName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldFirstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldFirstNamejTextFieldOnlyAplhabeticKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("City:");

        jTextFieldFirstName1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldFirstName1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldFirstName1jTextFieldOnlyAplhabeticKeyTyped(evt);
            }
        });

        jTextFieldFirstName2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Street:");

        jFormattedTextFieldBirthdate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###"))));

        jLabelBirthdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelBirthdate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelBirthdate.setText("House number:");

        jLabelBirthdate1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelBirthdate1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelBirthdate1.setText("Area code:");

        jFormattedTextFieldBirthdate1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###"))));

        jLabelBirthdate2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelBirthdate2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelBirthdate2.setText("Zip code:");

        jFormattedTextFieldBirthdate2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###"))));

        jLabelBirthdate4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelBirthdate4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelBirthdate4.setText("Area code:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Permament Address");

        jFormattedTextFieldBirthdate4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###"))));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("State:");

        jLabelBirthdate5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelBirthdate5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelBirthdate5.setText("Zip code:");

        jTextFieldFirstName4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldFirstName4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldFirstName4jTextFieldOnlyAplhabeticKeyTyped(evt);
            }
        });

        jFormattedTextFieldBirthdate5.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###"))));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("City:");

        jTextFieldFirstName5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldFirstName5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldFirstName5jTextFieldOnlyAplhabeticKeyTyped(evt);
            }
        });

        jTextFieldFirstName6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Street:");

        jFormattedTextFieldBirthdate6.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###"))));

        jLabelBirthdate6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelBirthdate6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelBirthdate6.setText("House number:");

        jFormattedTextFieldPhoneNum.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("+#############"))));
        jFormattedTextFieldPhoneNum.setToolTipText("+385");

        jLabelBirthdate7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelBirthdate7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelBirthdate7.setText("Telephone (Work):");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Present Address");

        jFormattedTextFieldPhoneNum1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("+#############"))));
        jFormattedTextFieldPhoneNum1.setToolTipText("+385");

        jLabelBirthdate8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelBirthdate8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelBirthdate8.setText("Telephone (Home):");

        jFormattedTextFieldPhoneNum2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("+#############"))));
        jFormattedTextFieldPhoneNum2.setToolTipText("+385");

        jLabelBirthdate9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelBirthdate9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelBirthdate9.setText("Mobile:");

        jTextFieldFirstName7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldFirstName7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldFirstName7jTextFieldOnlyAplhabeticKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Pager:");

        jTextFieldFirstName8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldFirstName8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldFirstName8jTextFieldOnlyAplhabeticKeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Fax:");

        jTextFieldFirstName9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldFirstName9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldFirstName9jTextFieldOnlyAplhabeticKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Email:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jLabel10))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldFirstName1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelBirthdate2)
                                    .addComponent(jLabelBirthdate1)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabelBirthdate))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFormattedTextFieldBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldFirstName2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextFieldBirthdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextFieldBirthdate2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(103, 103, 103)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldFirstName4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldFirstName5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelBirthdate5)
                                .addComponent(jLabelBirthdate4)
                                .addComponent(jLabel9)
                                .addComponent(jLabelBirthdate6))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jFormattedTextFieldBirthdate6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldFirstName6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jFormattedTextFieldBirthdate4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jFormattedTextFieldBirthdate5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelBirthdate7)
                        .addGap(18, 18, 18)
                        .addComponent(jFormattedTextFieldPhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabelBirthdate9)
                            .addGap(18, 18, 18)
                            .addComponent(jFormattedTextFieldPhoneNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabelBirthdate8)
                            .addGap(18, 18, 18)
                            .addComponent(jFormattedTextFieldPhoneNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldFirstName8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldFirstName9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldFirstName7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(218, 218, 218))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(365, 365, 365))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldFirstName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldFirstName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelBirthdate)
                            .addComponent(jFormattedTextFieldBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelBirthdate1)
                            .addComponent(jFormattedTextFieldBirthdate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelBirthdate2)
                            .addComponent(jFormattedTextFieldBirthdate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextFieldFirstName4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextFieldFirstName5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextFieldFirstName6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelBirthdate6)
                            .addComponent(jFormattedTextFieldBirthdate6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelBirthdate4)
                            .addComponent(jFormattedTextFieldBirthdate4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelBirthdate5)
                            .addComponent(jFormattedTextFieldBirthdate5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldPhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBirthdate7)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldFirstName9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldPhoneNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBirthdate8)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldFirstName8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldPhoneNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBirthdate9)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jTextFieldFirstName7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Contact Details", jPanel2);

        jFormattedTextFieldPhoneNum3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("+#############"))));
        jFormattedTextFieldPhoneNum3.setToolTipText("+385");

        jLabelBirthdate10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelBirthdate10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelBirthdate10.setText("Mobile:");

        jTextFieldFirstName10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldFirstName10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldFirstName10jTextFieldOnlyAplhabeticKeyTyped(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Pager:");

        jTextFieldFirstName11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldFirstName11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldFirstName11jTextFieldOnlyAplhabeticKeyTyped(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Fax:");

        jTextFieldFirstName12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldFirstName12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldFirstName12jTextFieldOnlyAplhabeticKeyTyped(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Email:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Telephones/Fax/Email");

        jFormattedTextFieldPhoneNum4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("+#############"))));
        jFormattedTextFieldPhoneNum4.setToolTipText("+385");

        jLabelBirthdate11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelBirthdate11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelBirthdate11.setText("Telephone (Work):");

        jFormattedTextFieldPhoneNum5.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("+#############"))));
        jFormattedTextFieldPhoneNum5.setToolTipText("+385");

        jLabelBirthdate12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelBirthdate12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelBirthdate12.setText("Telephone (Home):");

        jLabelFirstname4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelFirstname4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelFirstname4.setText("First name:");

        jTextFieldFirstName13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldFirstName13jTextFieldOnlyAplhabeticKeyTyped(evt);
            }
        });

        jLabelMiddle4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelMiddle4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelMiddle4.setText("Middle name:");

        jTextFieldMiddleName4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldMiddleName4KeyTyped(evt);
            }
        });

        jTextFieldSurname4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldSurname4KeyTyped(evt);
            }
        });

        jLabelSurname4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelSurname4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelSurname4.setText("Surname:");

        jLabelBirthdate13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelBirthdate13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelBirthdate13.setText("Area code:");

        jFormattedTextFieldBirthdate7.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###"))));

        jLabelBirthdate14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelBirthdate14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelBirthdate14.setText("Zip code:");

        jFormattedTextFieldBirthdate8.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###"))));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("State:");

        jTextFieldFirstName14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldFirstName14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldFirstName14jTextFieldOnlyAplhabeticKeyTyped(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Basic data");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("City:");

        jTextFieldFirstName15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldFirstName15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldFirstName15jTextFieldOnlyAplhabeticKeyTyped(evt);
            }
        });

        jTextFieldFirstName16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Street:");

        jFormattedTextFieldBirthdate9.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###"))));

        jLabelBirthdate15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelBirthdate15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelBirthdate15.setText("House number:");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Present Address");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabelBirthdate11)
                                .addGap(18, 18, 18)
                                .addComponent(jFormattedTextFieldPhoneNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabelBirthdate10)
                                    .addGap(18, 18, 18)
                                    .addComponent(jFormattedTextFieldPhoneNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabelBirthdate12)
                                    .addGap(18, 18, 18)
                                    .addComponent(jFormattedTextFieldPhoneNum5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldFirstName11, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldFirstName12, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldFirstName10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(183, 183, 183))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelFirstname4)
                                    .addComponent(jLabelMiddle4)
                                    .addComponent(jLabelSurname4))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldSurname4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldFirstName13, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldMiddleName4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldFirstName14, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldFirstName15, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addComponent(jLabel21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldFirstName16, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelBirthdate15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextFieldBirthdate9, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabelBirthdate14))
                            .addComponent(jLabelBirthdate13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTextFieldBirthdate7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldBirthdate8, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(132, 132, 132))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel17)
                    .addComponent(jLabel19))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFirstname4)
                    .addComponent(jTextFieldFirstName13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMiddle4)
                    .addComponent(jTextFieldMiddleName4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSurname4)
                    .addComponent(jTextFieldSurname4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jTextFieldFirstName14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)
                            .addComponent(jTextFieldFirstName16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jTextFieldFirstName15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelBirthdate15)
                            .addComponent(jFormattedTextFieldBirthdate9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelBirthdate13)
                            .addComponent(jFormattedTextFieldBirthdate7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelBirthdate14)
                            .addComponent(jFormattedTextFieldBirthdate8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldPhoneNum4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBirthdate11)
                    .addComponent(jLabel16)
                    .addComponent(jTextFieldFirstName12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldPhoneNum5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBirthdate12)
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldFirstName11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldPhoneNum3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBirthdate10)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldFirstName10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        jTabbedPane1.addTab("Contact Next-of-Kin", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 851, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 549, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Personal Details", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 851, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 549, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Lifestyle", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 851, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 549, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Basic Complaints", jPanel6);

        jButtonCancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonCancel.setText("Cancel");
        jButtonCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCancelMouseClicked(evt);
            }
        });

        jButtonAdd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonAdd.setText("Add");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLabelExtensiveForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 856, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JLabelExtensiveForm, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldFirstName3jTextFieldOnlyAplhabeticKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFirstName3jTextFieldOnlyAplhabeticKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFirstName3jTextFieldOnlyAplhabeticKeyTyped

    private void jTextFieldMiddleName3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMiddleName3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMiddleName3KeyTyped

    private void jTextFieldSurname3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSurname3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSurname3KeyTyped

    private void jTextFieldFirstNamejTextFieldOnlyAplhabeticKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFirstNamejTextFieldOnlyAplhabeticKeyTyped
        char c = evt.getKeyChar();

        if (!(Character.isAlphabetic(c) || (c == KeyEvent.VK_BACKSPACE) || c == KeyEvent.VK_DELETE || c == KeyEvent.VK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldFirstNamejTextFieldOnlyAplhabeticKeyTyped

    private void jTextFieldFirstName1jTextFieldOnlyAplhabeticKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFirstName1jTextFieldOnlyAplhabeticKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFirstName1jTextFieldOnlyAplhabeticKeyTyped

    private void jTextFieldFirstName4jTextFieldOnlyAplhabeticKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFirstName4jTextFieldOnlyAplhabeticKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFirstName4jTextFieldOnlyAplhabeticKeyTyped

    private void jTextFieldFirstName5jTextFieldOnlyAplhabeticKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFirstName5jTextFieldOnlyAplhabeticKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFirstName5jTextFieldOnlyAplhabeticKeyTyped

    private void jTextFieldFirstName7jTextFieldOnlyAplhabeticKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFirstName7jTextFieldOnlyAplhabeticKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFirstName7jTextFieldOnlyAplhabeticKeyTyped

    private void jTextFieldFirstName8jTextFieldOnlyAplhabeticKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFirstName8jTextFieldOnlyAplhabeticKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFirstName8jTextFieldOnlyAplhabeticKeyTyped

    private void jTextFieldFirstName9jTextFieldOnlyAplhabeticKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFirstName9jTextFieldOnlyAplhabeticKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFirstName9jTextFieldOnlyAplhabeticKeyTyped

    private void jButtonCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCancelMouseClicked
        dispose();
    }//GEN-LAST:event_jButtonCancelMouseClicked

    private void jTextFieldFirstName10jTextFieldOnlyAplhabeticKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFirstName10jTextFieldOnlyAplhabeticKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFirstName10jTextFieldOnlyAplhabeticKeyTyped

    private void jTextFieldFirstName11jTextFieldOnlyAplhabeticKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFirstName11jTextFieldOnlyAplhabeticKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFirstName11jTextFieldOnlyAplhabeticKeyTyped

    private void jTextFieldFirstName12jTextFieldOnlyAplhabeticKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFirstName12jTextFieldOnlyAplhabeticKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFirstName12jTextFieldOnlyAplhabeticKeyTyped

    private void jTextFieldFirstName13jTextFieldOnlyAplhabeticKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFirstName13jTextFieldOnlyAplhabeticKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFirstName13jTextFieldOnlyAplhabeticKeyTyped

    private void jTextFieldMiddleName4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMiddleName4KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMiddleName4KeyTyped

    private void jTextFieldSurname4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSurname4KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSurname4KeyTyped

    private void jTextFieldFirstName14jTextFieldOnlyAplhabeticKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFirstName14jTextFieldOnlyAplhabeticKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFirstName14jTextFieldOnlyAplhabeticKeyTyped

    private void jTextFieldFirstName15jTextFieldOnlyAplhabeticKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFirstName15jTextFieldOnlyAplhabeticKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFirstName15jTextFieldOnlyAplhabeticKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExtensiveForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExtensiveForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExtensiveForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExtensiveForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ExtensiveForm dialog = new ExtensiveForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelExtensiveForm;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JComboBox<String> jComboBoxSex3;
    private javax.swing.JFormattedTextField jFormattedTextFieldBirthdate;
    private javax.swing.JFormattedTextField jFormattedTextFieldBirthdate1;
    private javax.swing.JFormattedTextField jFormattedTextFieldBirthdate2;
    private javax.swing.JFormattedTextField jFormattedTextFieldBirthdate3;
    private javax.swing.JFormattedTextField jFormattedTextFieldBirthdate4;
    private javax.swing.JFormattedTextField jFormattedTextFieldBirthdate5;
    private javax.swing.JFormattedTextField jFormattedTextFieldBirthdate6;
    private javax.swing.JFormattedTextField jFormattedTextFieldBirthdate7;
    private javax.swing.JFormattedTextField jFormattedTextFieldBirthdate8;
    private javax.swing.JFormattedTextField jFormattedTextFieldBirthdate9;
    private javax.swing.JFormattedTextField jFormattedTextFieldPhoneNum;
    private javax.swing.JFormattedTextField jFormattedTextFieldPhoneNum1;
    private javax.swing.JFormattedTextField jFormattedTextFieldPhoneNum2;
    private javax.swing.JFormattedTextField jFormattedTextFieldPhoneNum3;
    private javax.swing.JFormattedTextField jFormattedTextFieldPhoneNum4;
    private javax.swing.JFormattedTextField jFormattedTextFieldPhoneNum5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBirthdate;
    private javax.swing.JLabel jLabelBirthdate1;
    private javax.swing.JLabel jLabelBirthdate10;
    private javax.swing.JLabel jLabelBirthdate11;
    private javax.swing.JLabel jLabelBirthdate12;
    private javax.swing.JLabel jLabelBirthdate13;
    private javax.swing.JLabel jLabelBirthdate14;
    private javax.swing.JLabel jLabelBirthdate15;
    private javax.swing.JLabel jLabelBirthdate2;
    private javax.swing.JLabel jLabelBirthdate3;
    private javax.swing.JLabel jLabelBirthdate4;
    private javax.swing.JLabel jLabelBirthdate5;
    private javax.swing.JLabel jLabelBirthdate6;
    private javax.swing.JLabel jLabelBirthdate7;
    private javax.swing.JLabel jLabelBirthdate8;
    private javax.swing.JLabel jLabelBirthdate9;
    private javax.swing.JLabel jLabelFirstname3;
    private javax.swing.JLabel jLabelFirstname4;
    private javax.swing.JLabel jLabelMiddle3;
    private javax.swing.JLabel jLabelMiddle4;
    private javax.swing.JLabel jLabelSex3;
    private javax.swing.JLabel jLabelSurname3;
    private javax.swing.JLabel jLabelSurname4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextFieldFirstName;
    private javax.swing.JTextField jTextFieldFirstName1;
    private javax.swing.JTextField jTextFieldFirstName10;
    private javax.swing.JTextField jTextFieldFirstName11;
    private javax.swing.JTextField jTextFieldFirstName12;
    private javax.swing.JTextField jTextFieldFirstName13;
    private javax.swing.JTextField jTextFieldFirstName14;
    private javax.swing.JTextField jTextFieldFirstName15;
    private javax.swing.JTextField jTextFieldFirstName16;
    private javax.swing.JTextField jTextFieldFirstName2;
    private javax.swing.JTextField jTextFieldFirstName3;
    private javax.swing.JTextField jTextFieldFirstName4;
    private javax.swing.JTextField jTextFieldFirstName5;
    private javax.swing.JTextField jTextFieldFirstName6;
    private javax.swing.JTextField jTextFieldFirstName7;
    private javax.swing.JTextField jTextFieldFirstName8;
    private javax.swing.JTextField jTextFieldFirstName9;
    private javax.swing.JTextField jTextFieldMiddleName3;
    private javax.swing.JTextField jTextFieldMiddleName4;
    private javax.swing.JTextField jTextFieldSurname3;
    private javax.swing.JTextField jTextFieldSurname4;
    // End of variables declaration//GEN-END:variables
}
