/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.krispeklaric.virgohospital_gui;

import com.krispeklaric.virgohospital_bl.AddressBL;
import com.krispeklaric.virgohospital_bl.BasicComplaintBL;
import com.krispeklaric.virgohospital_bl.ContactDetailBL;
import com.krispeklaric.virgohospital_bl.DoctorBL;
import com.krispeklaric.virgohospital_bl.MedicalComplaintBL;
import com.krispeklaric.virgohospital_bl.Messages.address.InsertAddressResult;
import com.krispeklaric.virgohospital_bl.Messages.basic_complaint.InsertBasicComplaintResult;
import com.krispeklaric.virgohospital_bl.Messages.contact_detail.InsertContactDetailResult;
import com.krispeklaric.virgohospital_bl.Messages.doctor.GetDoctorResult;
import com.krispeklaric.virgohospital_bl.Messages.medical_complaint.InsertMedicalComplaintResult;
import com.krispeklaric.virgohospital_bl.Messages.next_of_kin.InsertNextOfKinResult;
import com.krispeklaric.virgohospital_bl.Messages.patient.InsertPatientResult;
import com.krispeklaric.virgohospital_bl.Messages.patient_lifestyle.InsertPatientLifestyleResult;
import com.krispeklaric.virgohospital_bl.Messages.personal_details.InsertPersonalDetailResult;
import com.krispeklaric.virgohospital_bl.Messages.phone_number.InsertPhoneNumberResult;
import com.krispeklaric.virgohospital_bl.NextOfKinBL;
import com.krispeklaric.virgohospital_bl.PatientLifestyleBL;
import com.krispeklaric.virgohospital_bl.PatientsBL;
import com.krispeklaric.virgohospital_bl.PersonalDetailsBL;
import com.krispeklaric.virgohospital_bl.PhoneNumberBL;
import com.krispeklaric.virgohospital_dal.Models.Address;
import com.krispeklaric.virgohospital_dal.Models.BasicComplaint;
import com.krispeklaric.virgohospital_dal.Models.ContactDetail;
import com.krispeklaric.virgohospital_dal.Models.Doctor;
import com.krispeklaric.virgohospital_dal.Models.MedicalComplaint;
import com.krispeklaric.virgohospital_dal.Models.NextOfKin;
import com.krispeklaric.virgohospital_dal.Models.Patient;
import com.krispeklaric.virgohospital_dal.Models.PatientLifestyle;
import com.krispeklaric.virgohospital_dal.Models.PersonalDetail;
import com.krispeklaric.virgohospital_dal.Models.PhoneNumber;
import com.krispeklaric.virgohospital_dal.Models.PhoneType;
import com.sun.glass.events.KeyEvent;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author Kris
 */
public class SimpleForm extends javax.swing.JDialog {

    public SimpleForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCancel = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jLabelTitle = new javax.swing.JLabel();
        jLabelMiddle = new javax.swing.JLabel();
        jLabelSurname = new javax.swing.JLabel();
        jLabelSex = new javax.swing.JLabel();
        jLabelBirthdate = new javax.swing.JLabel();
        jLabelBrief = new javax.swing.JLabel();
        jLabelContact1 = new javax.swing.JLabel();
        jLabelFirstnameKin = new javax.swing.JLabel();
        jLabelMiddlenameKin = new javax.swing.JLabel();
        jLabelSurnameKin = new javax.swing.JLabel();
        jLabelOutpatientRelationship = new javax.swing.JLabel();
        jLabelFirstname = new javax.swing.JLabel();
        jTextFieldFirstName = new javax.swing.JTextField();
        jTextFieldMiddleName = new javax.swing.JTextField();
        jTextFieldSurname = new javax.swing.JTextField();
        jComboBoxSex = new javax.swing.JComboBox<>();
        jFormattedTextFieldBirthdate = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaStateOfComplaint = new javax.swing.JTextArea();
        jLabel1Contact2 = new javax.swing.JLabel();
        jFormattedTextFieldPhoneNum1 = new javax.swing.JFormattedTextField();
        jFormattedTextFieldPhoneNum2 = new javax.swing.JFormattedTextField();
        jTextFieldFirstNameKin = new javax.swing.JTextField();
        jTextFieldMiddleNameKin = new javax.swing.JTextField();
        jTextFieldSurnameKin = new javax.swing.JTextField();
        jTextFieldRelationshipOutpatient = new javax.swing.JTextField();
        jComboBoxContactCombo1 = new javax.swing.JComboBox<>();
        jComboBoxContactCombo2 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        jButtonCancel.setText("Cancel");
        jButtonCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCancelMouseClicked(evt);
            }
        });

        jButtonAdd.setText("Add");
        jButtonAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAddMouseClicked(evt);
            }
        });

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("Mini registration form");

        jLabelMiddle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelMiddle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelMiddle.setText("Middle name:");

        jLabelSurname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelSurname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelSurname.setText("Surname:");

        jLabelSex.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelSex.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelSex.setText("Sex(M/F):");

        jLabelBirthdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelBirthdate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelBirthdate.setText("Date of Birth(dd/mm/yyyy):");

        jLabelBrief.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelBrief.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelBrief.setText("Brief statement of Complaint:");

        jLabelContact1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelContact1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelContact1.setText("Contact telephone number 1:");

        jLabelFirstnameKin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelFirstnameKin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelFirstnameKin.setText("First name:");

        jLabelMiddlenameKin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelMiddlenameKin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelMiddlenameKin.setText("Middle name:");

        jLabelSurnameKin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelSurnameKin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelSurnameKin.setText("Surname:");

        jLabelOutpatientRelationship.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelOutpatientRelationship.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelOutpatientRelationship.setText("Relationship to outpatient:");

        jLabelFirstname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelFirstname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelFirstname.setText("First name:");

        jTextFieldFirstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldOnlyAplhabeticKeyTyped(evt);
            }
        });

        jTextFieldMiddleName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldMiddleNameKeyTyped(evt);
            }
        });

        jTextFieldSurname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldSurnameKeyTyped(evt);
            }
        });

        jComboBoxSex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));

        jFormattedTextFieldBirthdate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        jFormattedTextFieldBirthdate.setText("01/01/2000");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextAreaStateOfComplaint.setColumns(20);
        jTextAreaStateOfComplaint.setLineWrap(true);
        jTextAreaStateOfComplaint.setRows(5);
        jTextAreaStateOfComplaint.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextAreaStateOfComplaint);

        jLabel1Contact2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1Contact2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1Contact2.setText("Contact telephone number 2:");

        jFormattedTextFieldPhoneNum1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#############"))));
        jFormattedTextFieldPhoneNum1.setToolTipText("+385");

        jFormattedTextFieldPhoneNum2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#############"))));
        jFormattedTextFieldPhoneNum2.setToolTipText("+385");

        jTextFieldFirstNameKin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldFirstNameKinKeyTyped(evt);
            }
        });

        jTextFieldMiddleNameKin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldMiddleNameKinKeyTyped(evt);
            }
        });

        jTextFieldSurnameKin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldSurnameKinKeyTyped(evt);
            }
        });

        jTextFieldRelationshipOutpatient.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldRelationshipOutpatientKeyTyped(evt);
            }
        });

        jComboBoxContactCombo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Work", "Mobile", "Home" }));

        jComboBoxContactCombo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mobile", "Work", "Home" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Next of Kin");
        jLabel2.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(87, 87, 87)
                                    .addComponent(jLabelBirthdate))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(181, 181, 181)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelFirstname, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelMiddle, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelSurname, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelSex, javax.swing.GroupLayout.Alignment.TRAILING))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelFirstnameKin)
                                    .addComponent(jLabelMiddlenameKin)
                                    .addComponent(jLabelSurnameKin)
                                    .addComponent(jLabelBrief)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabelOutpatientRelationship))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1Contact2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBoxContactCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelContact1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBoxContactCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxSex, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextFieldBirthdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldRelationshipOutpatient, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldFirstNameKin)
                                            .addComponent(jTextFieldMiddleNameKin)
                                            .addComponent(jTextFieldSurnameKin, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldFirstName)
                                    .addComponent(jTextFieldMiddleName)
                                    .addComponent(jTextFieldSurname)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jFormattedTextFieldPhoneNum1)
                                    .addComponent(jFormattedTextFieldPhoneNum2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(207, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFirstname)
                    .addComponent(jTextFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMiddle)
                    .addComponent(jTextFieldMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSurname)
                    .addComponent(jTextFieldSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSex)
                    .addComponent(jComboBoxSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBirthdate)
                    .addComponent(jFormattedTextFieldBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBrief))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelContact1)
                    .addComponent(jFormattedTextFieldPhoneNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxContactCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1Contact2)
                    .addComponent(jFormattedTextFieldPhoneNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxContactCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFirstnameKin)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldFirstNameKin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldMiddleNameKin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMiddlenameKin))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldSurnameKin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSurnameKin))))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOutpatientRelationship)
                    .addComponent(jTextFieldRelationshipOutpatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCancelMouseClicked
        dispose();
    }//GEN-LAST:event_jButtonCancelMouseClicked

    private void jTextFieldOnlyAplhabeticKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldOnlyAplhabeticKeyTyped
        char c = evt.getKeyChar();

        if (!(Character.isAlphabetic(c) || (c == KeyEvent.VK_BACKSPACE) || c == KeyEvent.VK_DELETE || c == KeyEvent.VK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldOnlyAplhabeticKeyTyped

    private void jTextFieldMiddleNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMiddleNameKeyTyped
        jTextFieldOnlyAplhabeticKeyTyped(evt);
    }//GEN-LAST:event_jTextFieldMiddleNameKeyTyped

    private void jTextFieldSurnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSurnameKeyTyped
        jTextFieldOnlyAplhabeticKeyTyped(evt);
    }//GEN-LAST:event_jTextFieldSurnameKeyTyped

    private void jTextFieldFirstNameKinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFirstNameKinKeyTyped
        jTextFieldOnlyAplhabeticKeyTyped(evt);
    }//GEN-LAST:event_jTextFieldFirstNameKinKeyTyped

    private void jTextFieldMiddleNameKinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMiddleNameKinKeyTyped
        jTextFieldOnlyAplhabeticKeyTyped(evt);
    }//GEN-LAST:event_jTextFieldMiddleNameKinKeyTyped

    private void jTextFieldSurnameKinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSurnameKinKeyTyped
        jTextFieldOnlyAplhabeticKeyTyped(evt);
    }//GEN-LAST:event_jTextFieldSurnameKinKeyTyped

    private void jTextFieldRelationshipOutpatientKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRelationshipOutpatientKeyTyped
        jTextFieldOnlyAplhabeticKeyTyped(evt);
    }//GEN-LAST:event_jTextFieldRelationshipOutpatientKeyTyped

    private void jButtonAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddMouseClicked
        PatientsBL patientBL = new PatientsBL();
        BasicComplaintBL basicComplaintBL = new BasicComplaintBL();
        NextOfKinBL nextOfKinBL = new NextOfKinBL();
        ContactDetailBL contactDetailBL = new ContactDetailBL();
        PhoneNumberBL phoneNumberBL = new PhoneNumberBL();
        AddressBL addressBL = new AddressBL();
        DoctorBL doctorBL = new DoctorBL();
        MedicalComplaintBL medicalComplaintBL = new MedicalComplaintBL();
        PatientLifestyleBL patientLifestyleBL = new PatientLifestyleBL();
        PersonalDetailsBL personalDetailsBL = new PersonalDetailsBL();

        Patient patient = new Patient();
        patient.setFirstname(jTextFieldFirstName.getText());
        patient.setMiddlename(jTextFieldMiddleName.getText());
        patient.setLastname(jTextFieldSurname.getText());
        patient.setGender(jComboBoxSex.getSelectedItem().toString().charAt(0));

        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");

        LocalDate birthdate = LocalDate.parse(jFormattedTextFieldBirthdate.getText(), formatter);
        patient.setBirthdate(birthdate);

        NextOfKin kin = new NextOfKin();
        kin.setFirstname(jTextFieldFirstNameKin.getText());
        kin.setMiddlename(jTextFieldMiddleNameKin.getText());
        kin.setLastname(jTextFieldSurnameKin.getText());
        kin.setOutpatientRelationship(jTextFieldRelationshipOutpatient.getText());

        BasicComplaint basicComplaint = new BasicComplaint();
        basicComplaint.setComplaintStatement(jTextAreaStateOfComplaint.getText());

        ContactDetail contact = new ContactDetail();
        ContactDetail contactNextOfKin = new ContactDetail();

        PhoneNumber phone1 = new PhoneNumber();
        PhoneNumber phone2 = new PhoneNumber();

        phone1.setNumber(jFormattedTextFieldPhoneNum1.getText());
        phone2.setNumber(jFormattedTextFieldPhoneNum2.getText());

        phone1.setPhoneType(PhoneType.valueOf(jComboBoxContactCombo1.getSelectedItem().toString()));
        phone2.setPhoneType(PhoneType.valueOf(jComboBoxContactCombo2.getSelectedItem().toString()));

        try {
            InsertBasicComplaintResult res1 = basicComplaintBL.insertBasicComplaint(basicComplaint);
            if (res1.isOK) {
                patient.setBasicComplaints(res1.basicComplaint);
            }

            Address a1 = new Address();
            Address a2 = new Address();
            Address a3 = new Address();
            Address a4 = new Address();

            InsertAddressResult adr1 = addressBL.insertAddress(a1);
            InsertAddressResult adr2 = addressBL.insertAddress(a2);
            InsertAddressResult adr3 = addressBL.insertAddress(a3);
            InsertAddressResult adr4 = addressBL.insertAddress(a4);

            contact.setPermanentAddress(adr1.address);
            contact.setPresentAddress(adr2.address);

            contactNextOfKin.setPermanentAddress(adr3.address);
            contactNextOfKin.setPresentAddress(adr4.address);

            InsertContactDetailResult contactPatient = contactDetailBL.insertContactDetail(contact);
            InsertContactDetailResult resNextOfKinContact = contactDetailBL.insertContactDetail(contactNextOfKin);

            phone1.setContact(contactPatient.contactDetail);
            phone2.setContact(contactPatient.contactDetail);

            InsertPhoneNumberResult resPhone1 = phoneNumberBL.insertPhoneNumber(phone1);
            InsertPhoneNumberResult resPhone2 = phoneNumberBL.insertPhoneNumber(phone2);

            GetDoctorResult doctors = doctorBL.getAll();
            Doctor availableDoctor = doctors.doctors.stream().filter(doc -> doc.isUnavailable() == false).findFirst().orElse(null);

            if (availableDoctor != null) {
                patient.setDoctor(availableDoctor);
            }

            MedicalComplaint medCompl = new MedicalComplaint();
            PatientLifestyle patLife = new PatientLifestyle();
            PersonalDetail persDet = new PersonalDetail();

            InsertMedicalComplaintResult medical = new InsertMedicalComplaintResult();
            InsertPatientLifestyleResult lifestyle = new InsertPatientLifestyleResult();
            InsertPersonalDetailResult personal = new InsertPersonalDetailResult();

            medical = medicalComplaintBL.insertMedicalComplaint(medCompl);
            lifestyle = patientLifestyleBL.insertPatientLifestyle(patLife);
            personal = personalDetailsBL.insertContactDetail(persDet);

            patient.setContactDetail(contactPatient.contactDetail);
            patient.setMedicalComplaints(medical.medicalComplaint);
            patient.setPatientLifestyle(lifestyle.patientLifestyle);
            patient.setPersonalDetail(personal.personalDetail);

            InsertPatientResult res2 = patientBL.insertPatient(patient);
            if (res2.isOK) {
                kin.setPatient(res2.patient);
            }

            kin.setContactDetailNextOf(contactNextOfKin);
            InsertNextOfKinResult res3 = nextOfKinBL.insertNextOfKin(kin);
            if (res3.isOK) {
                dispose();
            }

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButtonAddMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimpleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimpleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimpleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimpleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SimpleForm dialog = new SimpleForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JComboBox<String> jComboBoxContactCombo1;
    private javax.swing.JComboBox<String> jComboBoxContactCombo2;
    private javax.swing.JComboBox<String> jComboBoxSex;
    private javax.swing.JFormattedTextField jFormattedTextFieldBirthdate;
    private javax.swing.JFormattedTextField jFormattedTextFieldPhoneNum1;
    private javax.swing.JFormattedTextField jFormattedTextFieldPhoneNum2;
    private javax.swing.JLabel jLabel1Contact2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelBirthdate;
    private javax.swing.JLabel jLabelBrief;
    private javax.swing.JLabel jLabelContact1;
    private javax.swing.JLabel jLabelFirstname;
    private javax.swing.JLabel jLabelFirstnameKin;
    private javax.swing.JLabel jLabelMiddle;
    private javax.swing.JLabel jLabelMiddlenameKin;
    private javax.swing.JLabel jLabelOutpatientRelationship;
    private javax.swing.JLabel jLabelSex;
    private javax.swing.JLabel jLabelSurname;
    private javax.swing.JLabel jLabelSurnameKin;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaStateOfComplaint;
    private javax.swing.JTextField jTextFieldFirstName;
    private javax.swing.JTextField jTextFieldFirstNameKin;
    private javax.swing.JTextField jTextFieldMiddleName;
    private javax.swing.JTextField jTextFieldMiddleNameKin;
    private javax.swing.JTextField jTextFieldRelationshipOutpatient;
    private javax.swing.JTextField jTextFieldSurname;
    private javax.swing.JTextField jTextFieldSurnameKin;
    // End of variables declaration//GEN-END:variables
}
